# Подключение к нашей базе данных careta_db
spring.datasource.url=jdbc:postgresql://localhost:5432/careta_db
spring.datasource.username=emilakmaev
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate для автоматического контроля таблиц
spring.jpa.hibernate.ddl-auto=update
# Включаем вывод SQL-запросов в терминал сервера для отладки
spring.jpa.show-sql=true